### ISSUE TITLE
MONGODB-X509 in version 6.0

### ISSUE THREAD

**Issue by talaikis** [Automattic/mongoose#11333]
Version 6+ stopped working for `MONGODB-X509` connections:

```
credentials must be an object with 'username' and 'password' properties
```

connecting with 

```
mongoose.connect(uri, {
      tls: true,
      tlsCAFile: ....,
      tlsCertificateKeyFile: ...,
      auth: {
        username: '...'
      },
      authMechanism: 'MONGODB-X509',
      replicaSet: '...'
    })
```

**Comment by Uzlopak** [comment]
When I read the sourcecode it seems, that you should not set a username anyway. So you should remove the username to get it working?!

**Comment by talaikis** [comment]
Yeah, does not work with or without username, same error.

**Comment by vkarpov15** [comment]
Looks like the MongoDB node driver team now recommends putting the username in the connection string for X509 auth. Instead of:

```javascript
mongoose.connect('mongodb://localhost:27017/test', {
      tls: true,
      tlsCAFile: ....,
      tlsCertificateKeyFile: ...,
      auth: {
        username: 'myusername'
      },
      authMechanism: 'MONGODB-X509',
      replicaSet: '...'
    })
```

Do:

```javascript
mongoose.connect('mongodb://myusername: localhost:27017/test', {
      tls: true,
      tlsCAFile: ....,
      tlsCertificateKeyFile: ...,
      authMechanism: 'MONGODB-X509',
      replicaSet: '...'
    })
```

Here's an example in their tests: https://github.com/mongodb/node-mongodb-native/blob/00be68fbc3b6b4b27858969dddbb9c595d5da9c6/test/integration/auth/ssl_x509_connect.test.js#L93-L105

**Comment by vkarpov15** [comment]
Fixed by https://github.com/Automattic/mongoose/commit/c379073a9d5a6ee27b32bce2c6ef6debfef1d6ef

**Comment by talaikis** [comment]
> credentials must be an object with 'username' and 'password' properties

That does not solve the problem, because username in X509 is a certificate string, which hardly can be encoded by URI component: `Mongoose connection Ac [MongoParseError]: Username contains unescaped characters`. Basically it's why it is used in the options body since the version 5.
