### ISSUE TITLE
Export node-mongodb-native types

### ISSUE THREAD

**Issue by LvChengbin** [Automattic/mongoose#11944]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Allow users to provide `node-mongodb-native` package manually.

### Motivation

Although mongoose provide a static `mongo` property reference to `node-mongodb-native` but it's hard to import some `class` from `node-mongodb-native` as `Type` in typescript.

I am going to implement a class similar to the code bellow:

```ts
class BucketService {
    bucket: typeof mongoose.mongo.GridFSBucket;
    constructor() {
        this.bucket = new mongoose.mongo.GridFSBucket( ... );
    }
}
```

In this case, error message is emitted from typescript compiler.

```
error TS2740: Type 'GridFSBucket' is missing the following properties from type 'typeof GridFSBucket': prototype, INDEX, getEventListeners, errorMonitor, and 4 more.
```

If I install `node-mongodb-native` in my package just for importing the `GridFSBucket` type, I have to keep it has same version with which in mongoose dependencies.

Otherwise, exporting types from `node-mongodb-native` to support syntax like `import { GridFSBucket } from 'mongoose/mongo` might be also make sense.

**Comment by vkarpov15** [comment]
We'll consider exporting all the types. But the better approach really is to keep the same version of node-mongodb-native in your `package.json` dependencies.

We're not likely to put node-mongodb-native as a peer dependency in the near future, because right now we think that supporting exactly 1 version of node-mongodb-native per version of Mongoose is better for maintainability.

**Comment by AbdelrahmanHafez** [comment]
From a usability point of view, I find exporting all MongoDB types as `mongoose/mongodb-driver` or `mongoose/mongodb-driver-types` seems like the best solution in terms of clear separation of types, and least maintenance cost.

@vkarpov15 Having to manually check for what version of the native driver mongoose is using, and adding it to package.json is not a very reliable way. Since we already have the driver as a dependency, I think we should be able to export types, and can't see a downside for anyone here.

What do you think?

**Comment by vkarpov15** [comment]
Yeah i think exporting the MongoDB driver types is a good option as long as we don't have to duplicate the types. If there's a 1-5 line solution, I'm all for it

**Comment by vkarpov15** [comment]
Fixed in #12948

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 Seems like this is not completely fixed.
On mongoose `8.2.0`, when I try:
```ts
import * as mongoose from 'mongoose';
mongoose.mongo.UpdateOptions; // `UpdateOptions` does not exist
```
If I uninstall `mongodb` as a separate dependency, I can:
```ts
import { UpdateOptions } from 'mongodb';
```

Is there any way with the current implementation we can access `UpdateOptions` without having to install `mongodb`?

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez I took a closer look and this looks like just a bad error message from TypeScript. Should more likely be a `'UpdateOptions' only refers to a type, but is being used as a value here.` error. For example, the following compiles fine:

```ts
import * as mongoose from 'mongoose';

const opts: mongoose.mongo.UpdateOptions = { upsert: true }; // works
```

It looks like TypeScript just occludes the "only refers to a type" error when you have a namespaced property.
