### ISSUE TITLE
Typescript types on "this" in instance methods

### ISSUE THREAD

**Issue by ozzyonfire** [Automattic/mongoose#13800]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.5.0

### Node.js version

18.x

### MongoDB version

5.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.5

### Issue

I am trying to get Typescript typings to work on instance methods defined on my schema. I've followed along in the docs, but I can only get types working on "this" that reflect methods, and not any properties.

Example schema (I pulled from a working example I found on here):
```ts
import { Model, Schema, model } from 'mongoose';

interface IUser {
	firstName: string;
	lastName: string;
}

// Put all user instance methods in this interface:
interface IUserMethods {
	fullName(): string;
}

// Create a new Model type that knows about IUserMethods...
type UserModel = Model<IUser, {}, IUserMethods>;

// And a schema that knows about IUserMethods
const schema = new Schema<IUser, UserModel, IUserMethods>({
	firstName: { type: String, required: true },
	lastName: { type: String, required: true },
});

schema.method('fullName', function fullName() {
	return this.firstName + ' ' + this.lastName;
});

const User = model<IUser, UserModel>('User', schema);

const user = new User({ firstName: 'Jean-Luc', lastName: 'Picard' });
user.firstName; // the typings here work great
const fullName: string = user.fullName(); // 'Jean-Luc Picard'
```

But my typescript doesn't give me the proper type of "this", "firstName" or "lastName"...
![image](https://github.com/Automattic/mongoose/assets/779491/618f6141-4911-4b54-bd74-fc38011a37a4)

I am upgrading my project from an older version of mongoose, typescript, etc. and I swear I used to have proper property types on this. 

Typescript version: 5.2.2
Node version 18 and my tsconfig is set up with "strict": true
``` json
{
	"extends": "@tsconfig/node18/tsconfig.json",
	"compilerOptions": {
		"strict": true,
		"strictNullChecks": true,
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true,
	}
}
```

Thanks for any insight!

**Comment by pshaddel** [comment]
I made this PR to fix this: https://github.com/Automattic/mongoose/pull/13822

**Comment by valeriuflorescu16** [comment]
I think you could update your schema as follows:
```
const schema = new Schema<IUser, UserModel, IUserMethods>({
	firstName: { type: String, required: true },
	lastName: { type: String, required: true },
}, {
	methods: {
		getFullName() {
			return `${this.firstName} ${this.lastName}`;
		}
	}
});
```
This way, the typing should work just fine. You can then delete the following:
```
schema.method('fullName', function fullName() {
	return this.firstName + ' ' + this.lastName;
});
```
Not sure if that works but it should I think.

**Comment by vkarpov15** [comment]
Fixed by #13822

**Comment by ozzyonfire** [comment]
I'm glad to see that this was fixed, but when will this be available in an official release? What is the release schedule like? Should this be marked closed if it's still not available in an official release?

**Comment by ruxxzebre** [comment]
Still having this issue, when using "methods" field on schema. Would be grateful for help! 
What works, is that if we remove methods from Schema generic, this will be typed as a document, but without my own declared methods.
1) providing IUserMethods
<img width="474" alt="Screenshot 2023-11-01 at 19 08 34" src="https://github.com/Automattic/mongoose/assets/54982966/64f25eb5-9f37-4b6d-8311-5ee913f60188">
2) w/o IUserMethods
<img width="385" alt="Screenshot 2023-11-01 at 19 10 09" src="https://github.com/Automattic/mongoose/assets/54982966/6e4cd0d2-32b7-478b-99f1-185ad24964f6">

**Comment by pshaddel** [comment]
@ruxxzebre I think this is another issue with `methods`. Could you open a new issue and add this code to the new issue? If you tag me I could take a look into this issue.

**Comment by ruxxzebre** [comment]
Will do. Thanks!
