### ISSUE TITLE
Mongoose 4.1+ error with bluebird (Cannot assign to read only property) 

### ISSUE THREAD

**Issue by mgcrea** [Automattic/mongoose#3286]
Encountering `TypeError: Cannot assign to read only property 'checkKeys' of true`.

Using:

```js
  schema.statics.createAsync = function() {
    return Promise.promisify(this.create).apply(this, arguments);
  };
```

Used to work with the `4.0` branch.

**Comment by pauliusuza** [comment]
+1 same error here, encountered using mongoose-auto-increment module

**Comment by BrandonCopley** [comment]
+1 - This is the same as 3293

**Comment by vkarpov15** [comment]
Hmm I'm having trouble reproducing this with any version of mongoose. Can you confirm which bluebird version you're using?

```javascript
var mongoose  = require('mongoose');
var Promise   = require('bluebird');
var Schema    = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh3286');

var schema = new Schema({ name: String });

schema.statics.createAsync = function() {
  return Promise.promisify(this.create).apply(this, arguments);
};

var MyModel = mongoose.model('test', schema);

MyModel.createAsync({ name: 'abc' }).then(function(v) {
  console.log('done');
  process.exit(0);
});
```

Seems to work fine, no exceptions

**Comment by BrandonCopley** [comment]
I'm not running bluebird I'm running passport-local-mongoose &
mongoose-timestamp

On Fri, Aug 28, 2015 at 1:11 PM, Valeri Karpov <notifications@github.com>
wrote:

> Hmm I'm having trouble reproducing this with any version of mongoose. Can
> you confirm which bluebird version you're using?
>
> var mongoose  = require('mongoose');var Promise   = require('bluebird');var Schema    = mongoose.Schema;
>
> mongoose.connect('mongodb://localhost/gh3286');
> var schema = new Schema({ name: String });
> schema.statics.createAsync = function() {
>   return Promise.promisify(this.create).apply(this, arguments);
> };
> var MyModel = mongoose.model('test', schema);
>
> MyModel.createAsync({ name: 'abc' }).then(function(v) {
>   console.log('done');
>   process.exit(0);
> });
>
> Seems to work fine, no exceptions
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/mongoose/issues/3286#issuecomment-135850666>
> .
>



-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060

e: copley.brandon@gmail.com

**Comment by vkarpov15** [comment]
Hmm can you show me a stack trace?

**Comment by BrandonCopley** [comment]
TypeError: Cannot assign to read only property 'checkKeys' of true
    at Collection.insertMany
(/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/mongodb/lib/collection.js:427:23)
    at Collection.insert
(/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/mongodb/lib/collection.js:668:15)
    at NativeCollection.(anonymous function) [as insert]
(/Users/brandoncopley/github/my_project/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:142:28)
    at /Users/brandoncopley/github/my_project/node_modules/mongoose/lib/model.js:116:24
    at new Promise.ES6
(/Users/brandoncopley/github/my_project/node_modules/mongoose/lib/promise.js:45:5)
    at model.$__handleSave
(/Users/brandoncopley/github/my_project/node_modules/mongoose/lib/model.js:102:12)
    at model.Model.save
(/Users/brandoncopley/github/my_project/node_modules/mongoose/lib/model.js:224:16)
    at model._done
(/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:101:24)
    at _next (/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:64:28)
    at fnWrapper
(/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
    at model.<anonymous>
(/Users/brandoncopley/github/my_project/node_modules/passport-local-mongoose/lib/passport-local-mongoose.js:72:9)
    at _next (/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper
(/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
    at model.Object.defineProperty.value.fn
(/Users/brandoncopley/github/my_project/node_modules/mongoose/lib/schema.js:213:9)
    at _next (/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper
(/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)


On Fri, Aug 28, 2015 at 1:28 PM, Valeri Karpov <notifications@github.com>
wrote:

> Hmm can you show me a stack trace?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/mongoose/issues/3286#issuecomment-135854279>
> .
>



-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060

e: copley.brandon@gmail.com

**Comment by BrandonCopley** [comment]
Maybe this would help?

    TypeError: Cannot assign to read only property 'checkKeys' of true
        at Collection.insertMany (/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/mongodb/lib/collection.js:427:23)
        at Collection.insert (/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/mongodb/lib/collection.js:668:15)
        at NativeCollection.(anonymous function) [as insert] (/Users/brandoncopley/github/my_project/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:142:28)
        at /Users/brandoncopley/github/my_project/node_modules/mongoose/lib/model.js:116:24
        at new Promise.ES6 (/Users/brandoncopley/github/my_project/node_modules/mongoose/lib/promise.js:45:5)
        at model.$__handleSave (/Users/brandoncopley/github/my_project/node_modules/mongoose/lib/model.js:102:12)
        at model.Model.save (/Users/brandoncopley/github/my_project/node_modules/mongoose/lib/model.js:224:16)
        at model._done (/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:101:24)
        at _next (/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:64:28)
        at fnWrapper (/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
        at model.<anonymous> (/Users/brandoncopley/github/my_project/node_modules/passport-local-mongoose/lib/passport-local-mongoose.js:72:9)
        at _next (/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
        at fnWrapper (/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
        at model.Object.defineProperty.value.fn (/Users/brandoncopley/github/my_project/node_modules/mongoose/lib/schema.js:213:9)
        at _next (/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
        at fnWrapper (/Users/brandoncopley/github/my_project/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)

**Comment by BrandonCopley** [comment]
Also, this error does NOT occur on the 4.1.1 branch. It's anything newer that breaks.

**Comment by napa3um** [comment]
code:

```
require('es6-promise').polyfill();
var mongoose = require('mongoose');

var PlaceSchema = new mongoose.Schema({
	title: { type: String, required: true },
	geo: { type: [Number], required: true, index: '2dsphere', unique: true }
}, { safe: true });

var PlaceModel = mongoose.model('Place', PlaceSchema, 'Place');

mongoose.connect(MONGO_URI, function(err){
	if(err)
		return console.log(err);

	var data = [{title: 'title1', geo: [50,50]}, {title: 'title2', geo: [51,51]}];
	var i = 0;
	(function rowIter(){
		if(i >= data.length)
			return;
		
		(function(i, row){
			new Promise(function(resolve, reject){
				PlaceModel.create({
					title: row.title,
					geo: row.geo
				}, function(err, doc){
					if(err)
						return reject(err);
					return resolve();
				});
			})
			.then(rowIter)
			.catch(function(err){
				console.log(err); // [TypeError: Cannot assign to read only property 'checkKeys' of true]
			});
		})(i, data[i]);
		
		i++;
	})();
});
```

**Comment by vkarpov15** [comment]
Looks like this was fixed in d9636bd7396491d1f6f58d5733e7f542530f4299, apparently another manifestation of #3222. Should be fixed now.

**Comment by gregthegeek** [comment]
I'm still having this issue with 4.1.4. Here's our stack trace:
````
Unhandled rejection TypeError: Cannot assign to read only property 'checkKeys' of true
    at Collection.insertMany (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/mongoose/node_modules/mongodb/lib/collection.js:427:23)
    at wrapped [as insertMany] (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/newrelic/lib/instrumentation/mongodb.js:177:25)
    at Collection.insert (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/mongoose/node_modules/mongodb/lib/collection.js:668:15)
    at wrapped [as insert] (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/newrelic/lib/instrumentation/mongodb.js:177:25)
    at NativeCollection.(anonymous function) [as insert] (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:142:28)
    at model.Model.$__handleSave (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/mongoose/lib/model.js:115:21)
    at /Users/greg/Documents/SchoolBee/sb-web/src/node_modules/mongoose/lib/model.js:221:11
    at new Promise.ES6 (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/mongoose/lib/promise.js:45:3)
    at model.Model.save (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/mongoose/lib/model.js:220:10)
    at model._done (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:101:24)
    at _next (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:64:28)
    at fnWrapper (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
    at model.Object.defineProperty.value.fn (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/mongoose/lib/schema.js:205:9)
    at _next (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at tryCatcher (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/bluebird/js/main/async.js:15:14)
    at Immediate._onImmediate (/Users/greg/Documents/SchoolBee/sb-web/src/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by vkarpov15** [comment]
@gregthegeek can you show me a code example as well? Stack trace is handy but code is much more helpful :)

**Comment by gregthegeek** [comment]
I still haven't been able to isolate a code example but I have found this: Running the latest version of mongoose (4.1.4) with mongodb driver 2.0.34 I do not get the problem. Changing the mongodb driver to 2.0.40 introduces the problem again.
