### ISSUE TITLE
Cannot connect to replica set over SSL: TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by leedm777** [Automattic/mongoose#3544]
I have a replica set which I connect to over SSL (the MongoDB+ service from compose.io). I can connect to it using the mongo command line tools, but trying to connect to it using mongoose I get a TypeError.

mongoose: v4.2.4
node.js: v0.10.40
mongodb: v3.0.6

```javascript
mongoose.connect('mongodb://user:password@aws-us-east-1-portal.X.dblayer.com:9999,aws-us-east-1-portal.Y.dblayer.com:8888/some-db?ssl=true', {
    replset: {
        ssl: true
        sslCA: ['-----BEGIN CERTIFICATE-----\n...']
    }
});
```

The error I get:

```
    TypeError: Cannot read property 'name' of undefined
        at [object Object].Server.equals (/usr/src/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1081:16)
        at [object Object].State.isPrimary (/usr/src/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset_state.js:71:39)
        at [object Object].State.update (/usr/src/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset_state.js:404:69)
        at processNewServer (/usr/src/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset.js:1159:27)
        at [object Object].<anonymous> (/usr/src/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/replset.js:1205:46)
        at [object Object].g (events.js:180:16)
        at [object Object].emit (events.js:95:17)
        at /usr/src/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:405:23
        at /usr/src/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:443:11
        at /usr/src/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/strategies/ping.js:264:5
        at /usr/src/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:765:13
        at [object Object].Callbacks.emit (/usr/src/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
        at [object Object].messageHandler (/usr/src/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
        at CleartextStream.<anonymous> (/usr/src/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
        at CleartextStream.emit (events.js:95:17)
        at CleartextStream.<anonymous> (_stream_readable.js:765:14)
```

**Comment by vkarpov15** [comment]
Looks like this was just fixed in the mongodb driver: https://github.com/christkv/mongodb-core/commit/56b295cc550cf8bf498a50384171cce14ada11ac . Will bump version when it's released to fix this.

**Comment by leedm777** [comment]
@vkarpov15 That fixes the crash, but mongoose still fails to connect.

I've stripped things down to a minimal app
```javascript
var mongoose = require('mongoose');
var secrets = require('./secrets');

[
  'connecting', 'connected', 'open', 'disconnecting', 'disconnected', 'close',
  'reconnected', 'error', 'fullsetup',
].forEach(function(ev) {
  mongoose.connection.on(ev, function(data) {
    if (typeof data !== 'undefined') {
      console.log(ev, JSON.stringify(data, null, 2));
    } else {
      console.log(ev);
    }
  });
});

mongoose.connect(secrets.URI, {
  user: secrets.USER,
  pass: secrets.PASSWORD,
  replset: {
    ssl: true,
    sslCA: secrets.CA
  },
}, function() {
  console.error('callback', arguments);
});
```

I see a `connecting` printed to the console, and the app exits about 10 seconds later.

**Comment by leedm777** [comment]
Okay, so the source of the problem was that I should have been using `mongos` instead of `replset`. After changing that, it connected fine.

Is this expected behavior, or should it emit an `error` event when it can't connect?

**Comment by vkarpov15** [comment]
Not 100% sure, I'll investigate later today.

**Comment by vkarpov15** [comment]
That's odd, running your script with a one-node sharded cluster I get the below output:

```
$ node gh-3544.js 
connecting
disconnected
callback { '0': 
   { [MongoError: server localhost:27000 sockets closed]
     name: 'MongoError',
     message: 'server localhost:27000 sockets closed' } }
```

```javascript
var mongoose = require('mongoose');

[
  'connecting', 'connected', 'open', 'disconnecting', 'disconnected', 'close',
  'reconnected', 'error', 'fullsetup',
].forEach(function(ev) {
  mongoose.connection.on(ev, function(data) {
    if (typeof data !== 'undefined') {
      console.log(ev, JSON.stringify(data, null, 2));
    } else {
      console.log(ev);
    }
  });
});

mongoose.connect('mongodb://localhost:27000', {
  replset: {
    ssl: true,
    sslCA: '/home/val/Workspace/10gen/mongo/jstests/lib/ca.pem'
  },
}, function() {
  console.error('callback', arguments);
});
```

Same thing happens with node 0.10 and 4.0. That's odd. Can you try running against a local mongod? Might be something weird on compose.io's end.

**Comment by leedm777** [comment]
I couldn't reproduce with local mongod, but I haven't tried it with either SSL or [mongos](https://docs.mongodb.org/manual/reference/program/mongos/) locally.

Unfortunately, I don't really have the time to set that sort of thing up right now :-(

Thanks for digging into it, though.

**Comment by vkarpov15** [comment]
That's unfortunate. Well, since I can't repo and you no longer have an issue, I'll consider this closed. Good luck, feel free to open up an issue if you have any more problems :)

**Comment by nickmarx12345678** [comment]
I'm still seeing this issue on 4.4.6

**Comment by nickmarx12345678** [comment]
@vkarpov15 so I believe I finally figured out what was causing this for us at least. Probably out of the scope of mongoose but we were (accidently) attempting to connect to several instances, when only one was available and specifically was not setup as a replset

example connection string being
`mongodb://127.0.0.1:27017/mydb,mongodb://127.0.0.1:27018/mydb,mongodb://127.0.0.1:27019/mydb`

where only the instance configured to port 27017 was available, and was not started/configured as part of a replset
