### ISSUE TITLE
Problem with tailable cursors on Mongo 3.2: `MongoError: Cursor not found`

### ISSUE THREAD

**Issue by letsgolesco** [Automattic/mongoose#3927]
Part of our app uses a tailable cursor on a capped collection. We've recently upgraded to MongoDB 3.2 and are connecting to the deployment through a mongos proxy using SSL.

Important note: this error does not occur on Mongoose 4.3.7 - we've only seen it happen when we try to use the latest 4.4 (currently 4.4.5).

Our connection options look like this:
```json
{
    "mongos": {
      "ssl": true,
      "sslValidate": true,
      "sslCA": [<SSL CA>],
      "socketOptions": {
        "keepAlive": 120
      }
    }
}
```

The code we're using to set up the tailable cursor looks like this:
```javascript
var stream = Model
    .find(query)
    .lean()
    .tailable(true, {
        awaitdata: false,
        numberOfRetries: Number.MAX_VALUE,
        tailableRetryInterval: 200
    })
    .stream();
```

And this is the stracktrace:
```
/api-server/node_modules/mongoose/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^
MongoError: Cursor not found (namespace: '<database>.<collection>', id: 9016619872637223506).
    at Function.MongoError.create (/api-server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at WireProtocol.getMore.queryCallback (/api-server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:183:34)
    at Callbacks.emit (/api-server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:116:3)
    at messageHandler (/api-server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:282:23)
    at TLSSocket.dataHandler (/api-server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:273:22)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
```

**Comment by vkarpov15** [comment]
I suspect this may have something to do with the mongodb driver. Will try to repro later, but please be patient - lots of new issues over the last couple weeks.

**Comment by tjwebb** [comment]
Any update on this? I'm running into this when using the stream() interface on mongoose

**Comment by vkarpov15** [comment]
Nope no update yet, I'm behind on issues and working on catching up.

**Comment by vkarpov15** [comment]
Here's my attempt to repro this - no luck, this script seems to run as expected for a while. Does this happen intermittently? Also, @tjwebb are you also using SSL? I don't think that SSL would cause this, but worth investigating if both of you are using SSL.

```javascript
'use strict';

const assert = require('assert');
const co = require('co');
const mongoose = require('mongoose');
const Topology = require('mongodb-topology-manager');

const topology = new Topology.Sharded({
  mongod: '/home/val/Workspace/10gen/mongodb-test-makefile/3.2.0/bin/mongod',
  mongos: '/home/val/Workspace/10gen/mongodb-test-makefile/3.2.0/bin/mongos',
});
let Model = null;

mongoose.set('debug', true);

co(function*() {
  yield topology.addShard([
    { options: { bind_ip: '127.0.0.1', port: 31000, dbpath: '/home/val/data/db2' } },
    { options: { bind_ip: '127.0.0.1', port: 31001, dbpath: '/home/val/data/db3' } },
    { options: { bind_ip: '127.0.0.1', port: 31002, dbpath: '/home/val/data/db4' } }
  ], { replSet: 'rs1' });

  yield topology.addConfigurationServers([{
    options: {
      bind_ip: '127.0.0.1', port: 35000, dbpath: '/home/val/data/db5'
    }
  }], { replSet: 'rs2' });

  yield topology.addProxies([{
    bind_ip: '127.0.0.1', port: 51000, configdb: '127.0.0.1:35000'
  }]);

  console.log('starting topology', require('util').inspect(topology, { depth: 15, colors: true }));

  yield topology.start();

  yield topology.enableSharding('test');

  Model = mongoose.model('Test', { name: String });

  yield mongoose.connect('mongodb://127.0.0.1:51000/gh3927', {
    "mongos": {
      "socketOptions": {
        "keepAlive": 120
      }
    }
  });
  yield mongoose.connection.db.createCollection('tests', { capped: true, size: 4096 });
}).then(function() {
  console.log('Starting stream!');

  var stream = Model
    .find()
    .lean()
    .tailable(true, {
        awaitdata: false,
        numberOfRetries: Number.MAX_VALUE,
        tailableRetryInterval: 200
    })
    .stream();

  stream.on('data', function(data) {
    console.log('data', data);
  });

  stream.on('error', function(error) {
    console.error(error);
    process.exit(1);
  });

  stream.on('end', function() {
    process.exit(0);
  });

  setInterval(function() {
    Model.create({ name: 'test' });
  }, 1000);
}).catch(function(error) {
  topology.stop().then(function() {
    console.error('==>', error, error.stack);
    process.exit(1);
  });
});
```

**Comment by vkarpov15** [comment]
Issue's been stale for a while, closing

**Comment by xyleads** [comment]
For others who are experiencing this issue, using mongoose 4.4.10 with MongoDB 3.2,  it was just fixed in mongodb-core version 1.3.13.

https://github.com/christkv/mongodb-core/commit/caa169de2c0ed67ed058ac0797c20fb6036bce3c

The MongoDB driver would intermittently throw errors of the form:

Cursor not found (namespace: '_some.collection_', id: 73106491510903863)."

This would mainly happen on find calls returning more than some random threshold of data.

I've used npm-shrinkwrap to bump Mpongoose's dependency of mongodb-core up to version 1.3.13 from 1.3.9. Hopefully, this version bump will come from the Mongoose team soon.

Regards,

Edvin

**Comment by dvideby0** [comment]
@xyleads We forked mongoose and bumped to 1.3.13 and we are still getting this issue. Con you confirm the fix actually worked for you?

**Comment by bobintornado** [comment]
I am using version 2.2.11 of mongodb, but still counter this issue on large collection over long time (occur after running more than 4 mins)

**Comment by vkarpov15** [comment]
Please provide code samples

**Comment by SunilAgrawal** [comment]
Even I am facing the same issue using the latest Mongoose version. Unfortunately don't have an isolated test case to provide at this point. 

This is happening in production for me :(

**Comment by bobintornado** [comment]
Workaround: 
If you know what you are doing (you actually know why this no cursor behaviour happened) and have a good reason, use `noCursorTimeout` flag on the cursor. 

`collection.find({}).addCursorFlag('noCursorTimeout', true)`

But be careful and manage the cursors on mongo server manually.

**Comment by kaiserdan** [comment]
` TypeError: Model.find(...).addCursorFlag is not a function` 

@bobintornado Got another idea on how to set the 'noCursorTimeout' timeout in mongoose@latest ?
