### ISSUE TITLE
Connection options for MongoDB driver are ignored

### ISSUE THREAD

**Issue by JasonCust** [Automattic/mongoose#6236]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
According to the [options documentation](http://mongoosejs.com/docs/connections.html#options), any MongoDB driver options can be specified via the mongoose connection method:
> The connect method also accepts an options object which will be passed on to the underlying MongoDB driver.

The linked [driver documentation](http://mongodb.github.io/node-mongodb-native/2.2/api/MongoClient.html#connect) includes an option to ignore `undefined` query params:
> ignoreUndefined | Boolean | false | optionalSpecify if the BSON serializer should ignore undefined fields

Also issue #6093 referenced a [link to the same option](https://github.com/mongodb/js-bson#why-does-undefined-get-converted-to-null) in a [comment](https://github.com/Automattic/mongoose/issues/6093#issuecomment-364293889) by @vkarpov15:
> Why does undefined get converted to null?
>
> The undefined BSON type has been deprecated for many years, so this library has dropped support for it. Use the `ignoreUndefined` option (for example, from the driver ) to instead remove undefined keys.

The expectation therefore is that by setting `ignoreUndefined` to `true`, any undefined query params would be ignored in the actual call to MongoDB.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
// connection made with an options object of: { ignoreUndefined: true }

const teamSchema = new mongoose.Schema({
  name: String,
  location: String
});

const Team = connection.model('Team', teamSchema);

const jedis = new Team({
  name: 'Jedis',
  location: 'Alderan'
});

jedis.save().then((jedis) => {
  const query = Team.find({name: 'Jedis', _id: undefined});

  console.log(query.getQuery());
  // Looks good here...
  // { name: 'Jedis', _id: undefined }
  //  lets send it!

  return query.exec()
  // HERE IS THE ISSUE
  // { name: 'Jedis', _id: null }
).then((jedis) => console.log);
// []
```

**What is the expected behavior?**
In the preceding repro-script, the expectation is that the query object sent from the MongoDB driver would be `{ name: 'Jedis' }` which would return an array containing one document. Instead the option appears to be ignored as the `_id` is equality checked with `null` which leads to no matching documents.

**Please mention your node.js, mongoose and MongoDB version.**

Node 8.9.4
MongoDB: 3.6
Mongoose: 5.0.10

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP

**Comment by vkarpov15** [comment]
Fixed in master, fix will be in 5.0.11

**Comment by bonesoul** [comment]
still not working for me; https://github.com/Automattic/mongoose/commit/cae03d379dda41b123aaeb07ad3c9ffba29fab35

**Comment by vkarpov15** [comment]
@bonesoul please open up a new issue with code samples.
