### ISSUE TITLE
Global strict mode configuration

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#6658]
https://github.com/Automattic/mongoose/issues/6578#issuecomment-402029769

`mongoose.set('strict', 'throw')` to make all schemas use `strict: 'throw'` by default.
`mongoose.set('strictQuery', 'throw')` to do the same for [`strictQuery`](http://mongoosejs.com/docs/guide.html#strictQuery)

**Comment by joeytwiddle** [comment]
### Why this is useful

Given a schema like this:
```js
const userSchema = new Schema({
  name: String,
  email: String,
});
```

it is quite common for one of our developers to forget what the names of the fields were:
```js
await User.create({
  userName: 'harry',
  emailAddress: 'harry@hogwarts.edu',
});
```

By default mongoose's behaviour would be to silently drop those fields, and create an empty document. This mistake won't be noticed when it is made. Only later, when the document is read back, will the developer notice the missing fields!

We find it preferable to catch that mistake at creation time, sooner rather than later, so it can be fixed quickly and easily.

**Comment by sebastian-nowak** [comment]
If you're planning to add this, I think it would be great to also have `mongoose.set('strictQuery', 'throw')`.

**Comment by vkarpov15** [comment]
Great suggestion, thanks @sebastian-nowak

**Comment by vkarpov15** [comment]
Fixed in 5.3 branch with https://github.com/Automattic/mongoose/commit/184c4771cf5107f20ee9ba1b39989020be668c99

**Comment by AbdelrahmanHafez** [comment]
`mongoose.set('strictQuery', 'throw');` still doesn't work.

### 6658.js
```js
'use strict';
const mongoose = require('./');
const { Schema } = mongoose;
const assert = require('assert');

mongoose.set('strictQuery', true);

const userSchema = new Schema({
  name: { type: String }
});

const User = mongoose.model('User', userSchema);

const filter = User.find({ notInSchema: 1 }).cast();
assert.ok(filter.notInSchema == null);

console.log('All assertions passed.');
```

### Output
```
Error: `strictQuery` is an invalid option.
```

### Output after adding it as a valid option
```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(filter.notInSchema == null)
```

mongoose v5.9.14

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 in cases like these, should we open a new issue, change the milestone, or just reopen and close by merging?

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez I'd err on the side of opening a new issue.

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 noted
