### ISSUE TITLE
'MongoNetworkError: failed to connect to server' when connecting ReplicaSet

### ISSUE THREAD

**Issue by yokingma** [Automattic/mongoose#7153]
I set up a 3 node replica set server with docker, it works fine

myhost:27017 =>172.18.0.2:27017  
myhost:27018 =>172.18.0.3:27017  
myhost:27019 =>172.18.0.4:27017  

but get error when try to connect :
```
{ MongoNetworkError: failed to connect to server [172.18.0.2:27017] on first connect [MongoNetworkError: connection 5 to 172.18.0.2:27017 timed out]
```

code:
```
const mongoose = require('mongoose')  
const opt = {  
    authSource: 'admin',
    replicaSet: 'replicaset',
    useNewUrlParser: true
}  
const uri = 'mongodb://user:password@myhost:27017,myhost:27018,myhost:27019/dbname'  

mongoose.connect(uri, opt).then(function () {
    console.log('Mongodb connect success!')
}, function (err) {
    console.log('Mongodb connect error: ', err)
})  
```

if connecting without ReplicaSet , works fine:
```
const opt = {  
    authSource: 'admin',
    useNewUrlParser: true
}  
const uri = 'mongodb://user:password@myhost:27017/dbname'  
```

mongoDB: 4.0.3
node: v8.11.3
mongoose: 5.3.4

Please help to find the problem

Thanks!

**Comment by vkarpov15** [comment]
Make sure the host names that running rs.conf() outputs line up with the ones in your connection string as described here: https://mongoosejs.com/docs/connections.html#replicaset-hostnames . That should fix it.

**Comment by bertero** [comment]
Hi @vkarpov15, I read the link you sent and it was clear.

Even so my issue persists. Let me explain a little further:

## What I have up and running
I've set up three containers (using docker-compose) running one mongo process inside each. Then I've started the replica set, by connecting with one of them and running all the `rs.initialize()` process.

`docker-compose.yml`:
```yml
version: "3"
services:
  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: mongo
    ports:
      - 127.0.0.1:27017:27017
    restart: always
    volumes:
      - ./mongo0/data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo
    ports:
      - 127.0.0.1:27018:27017
    restart: always
    volumes:
      - ./mongo1/data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo
    ports:
      - 127.0.0.1:27019:27017
    restart: always
    volumes:
      - ./mongo2/data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
```

`start-replica-set.sh`:
```shell
docker exec -it mongo0 mongo --eval " \
db = (new Mongo('localhost:27017')).getDB('test') && \
rs.initiate({ \
\"_id\":\"rs0\", \
\"members\":[ \
{\"_id\":0,\"host\":\"mongo0:27017\"}, \
{\"_id\":1,\"host\":\"mongo1:27018\"}, \
{\"_id\":2,\"host\":\"mongo2:27019\"} \
]})
"
```

MongoDB `connectionURI` used to connect via `mongoose`:
```js
const connectionURI = 'mongodb://mongo0:27017,mongo1:27017,mongo2:27017/test?replicaSet=rs0
```

## The issue

When I run a local test (outside the docker env) and try to connect using the `connectionURI` above mentioned, I get the error:
`MongoNetworkError: failed to connect to server [mongo1:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo1 mongo1:27017`.

Do you have any suggestions to run a MongoDB replica set inside a docker env and connect to it via `mongoose` when running local tests outside docker?

Thanks in advance.

**Comment by vkarpov15** [comment]
It looks like your node app can't resolve `mongo1`. Do you have an IP address for your docker containers?

Also, why are you running a replica set in docker?

**Comment by sibelius** [comment]
this is the common setup in a docker compose

**Comment by vkarpov15** [comment]
@sibelius are you having a similar issue?

**Comment by sibelius** [comment]
We are having the same issue

The problem is that mongoose or mongodb driver will try to resolve mongodb1 and mongodb2 even if you pass the localhost on connection string

We fixed this adding some mapping on /etc/hosts to map Docker IP address to mongodb1 and mongodb2

Kind of hack, but it works for now

**Comment by vkarpov15** [comment]
Yeah the /etc/hosts approach is one of the easy ways to fix this. If your MongoDB servers self resolved host name is "mongo1", then the MongoDB node driver will try to connect to "mongo1".

No way around it. You would either need to configure docker so hostname returns localhost in the MongoDB container, or make your app servers able to resolve the hostname.

**Comment by xiaobaidadada** [comment]
@vkarpov15 hope mongoose supports not reading replica set information in replica set mode. Because I don't want to keep replica second nodes to the public network，Would you consider supporting this feature

**Comment by vkarpov15** [comment]
@xiaobaidadada if you want to run a replica set but keep the secondary nodes not publicly available (i would not recommend doing that) then you should connect to the primary using the directConnection option.

**Comment by xiaobaidadada** [comment]
> [@xiaobaidadada](https://github.com/xiaobaidadada) if you want to run a replica set but keep the secondary nodes not publicly available (i would not recommend doing that) then you should connect to the primary using the directConnection option.

thanks
