### ISSUE TITLE
MongoTimeoutError: Server selection timed out after 30000 ms

### ISSUE THREAD

**Issue by Marko351** [Automattic/mongoose#8381]
**Do you want to request a *feature* or report a *bug*?**

a bug

**What is the current behavior?**
After updating to Mongoose 5.7.12, the following warning appeared:

>  MongoDB error when connecting: MongoTimeoutError: Server selection timed out after 30000 ms

When I try to connect to mongo Atlas I get above mentioned error
Here is code:
`const connectDB = async () => {`
`  try {`
`    const connection = await mongoose.connect(`
`      URI,`
`      {`
`        useCreateIndex: true,`
`        useNewUrlParser: true,`
`        useFindAndModify: false,`
`        useUnifiedTopology: true`
`      }`
`    )`
`    console.log('MongoDB connected: ${connection.connection.host}');`
`  } catch (error) {`
`    console.log('MongoDB error when connecting: ${error}');`
`  }`
`}`
`connectDB() `

**If the current behavior is a bug, please provide the steps to reproduce.**
see above

**What is the expected behavior?**
App should be connected with Atlas cluster. 

**What are the versions of Node.js, Mongoose and MongoDB you are using?**

I'm currently using: 
- Mongoose version 5.7.12
- NodeJS version 12.4.0
- MongoDB version 4.0.6
- MongoDB driver 3.3.4

**Comment by csilcock** [comment]
Seeing the same thing - looks like this should be addressed by [node-mongo-native release v3.3.5](https://github.com/mongodb/node-mongodb-native/releases/tag/v3.3.5). Looks like Mongoose has already bumped the driver version in master, so hopefully a release is pushed out to address this soon.

**Comment by micheleangioni** [comment]
Actually I am still getting this error, by using the newest Mongoose version `5.7.13` , which uses the `3.3.5` version of the mongo driver

**Comment by micheleangioni** [comment]
@csilcock as expected setting `useUnifiedTopology` to false fixes the problem. Any news on your side?

**Comment by vkarpov15** [comment]
Unfortunately I'm unable to repro this, even with Mongoose v5.7.12. The below script connects to Atlas as expected:

```javascript
'use strict';
  
const mongoose = require('mongoose');

const uri = 'mongodb+srv://user:pw@cluster0-OMITTED.mongodb.net/test?retryWrites=true&w=majority';

mongoose.connect(uri, { useUnifiedTopology: true, useNewUrlParser: true }).
  then(() => console.log('Connected')).
  catch(err => console.log('Caught', err.stack));
```

Please double check that your username and password are correct, and that you included your IP in your [Atlas IP whitelist](https://docs.atlas.mongodb.com/security-whitelist/).

**Comment by bekagaw653** [comment]
already solved at https://icetutor.com/question/mongodb-connection-error-mongotimeouterror-server-selection-timed-out-after-30000-ms/

**Comment by faridfadaie** [comment]
This is still an issue. We get this randomly when using Atlas (not it's not a whitelisting problem). All is fixed when useUnifiedTopology=false.

**Comment by DanielOToole-Portfolio** [comment]
even with useUnifiedTopology: false or true i still get a 'MongooseError [MongooseTimeoutError]: Server selection timed out after 30000 ms' error, anyone still getting this error?

**Comment by ChikaKanu** [comment]
I had similar problem, and through research got it solved via this stackoverflow answer on whitelisting the IP address via the network access in your cluster:
https://stackoverflow.com/questions/59162342/mongodb-connection-error-mongotimeouterror-server-selection-timed-out-after-30
I added my current IP and it worked.

**Comment by PizzaPartyInc** [comment]
Had a similar issue, here is the way it worked for me:

Connection string should be in a format: `mongodb://ip:port` and should not contain credentials or database name. Pass username, password and database name as options parameters. `useUnifiedTopology` shall be `true`. Could look like this:
```ts
mongoose.connect(
    'mongodb://ip:port',
    {
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useFindAndModify: false,
      useCreateIndex: true,
      user: 'username', // IMPORTANT TO HAVE IT HERE AND NOT IN CONNECTION STRING
      pass: 'password', // IMPORTANT TO HAVE IT HERE AND NOT IN CONNECTION STRING
      dbName: 'database-name', // IMPORTANT TO HAVE IT HERE AND NOT IN CONNECTION STRING
    },
    err => { throw err; },
  );
```
Additional Details:

- mongoose version 5.8.9
- mongodb version 3.5.1
- tried using connection string in a format `mongodb://username:password@ip:port/database-name`
- tried using connection string in a format `mongodb://ip:port/database-name` and passing only username and password as options
- in 2 cases above, setting `useUnifiedTopology` as `true` resulted in `MongooseTimeoutError: Server selection timed out after 30000 ms`
- in 2 cases above, setting `useUnifiedTopology` as `false` resulted in `MongoNetworkError: failed to connect to server [ip:port] on first connect [MongoError: Authentication failed.`

Questions:
- Why does supplying username, password and database name as part of connection string does not work for mongoose? I successfully connected with MongoClient using connection string with credentials in it (but not database name). And using `mongodb://localhost/database-name` obviously works...
- Also, `dbName` property comment states `database Name for Mongodb Atlas Connection`, but I was not using Atlas, it was set to run on local linux docker host. Maybe this and documentation for connection should be adjusted?

**Comment by ikb42** [comment]
One thing to bear in mind (which I found out the hard way) is the prefix:
mongodb+srv://
vs
mongodb://
